version: "3"

services:
  mongodb:
    image: mongo
    container_name: mongo
    volumes:
      - ./data:/data/db
    ports:
      - 27017:27017
    networks:
      - net
 
  ngnix:
    image: nginx
    container_name: nginx
    ports:
      - 80:80
    networks:
      - net

  fornt:
    build:
        context: ./front/.
        dockerfile: Dockerfile_Nginx
    environment:
      - FRONT_IP=fastapi-backend
      - PORT=8000
    image: react-nginx:latest
    container_name: react-nginx
    ports:
      - 8081:80
    networks:
      - net

  back:
    build:
        context: ./back/.
        dockerfile: Dockerfile
    environment:
        - DB_IP=mongo
        - DB_PORT=27017
    image: fastapi-backend:latest
    container_name: fastapi-backend 
    ports:
      - 8000:8000
    networks:
      - net

networks:
  net:
