version: "3"

services:
  mongodb:
    image: mongo
    container_name: mongo
    volumes:
      - ./data:/data/db
    ports:
      - 27017:27017
    networks:
      - net

  front:
    build:
      context: front
      dockerfile: Dockerfile_Nginx
    image: react-nginx:latest
    container_name: front
    ports:
      - 80:80
    environment:
      NODE_ENV: production
    networks:
      - net

  back:
    build:
      context: ./back/.
      dockerfile: Dockerfile
    environment:
      - DB_IP=mongo
    image: fastapi-backend:latest
    container_name: backend
    ports:
      - 8000:8000
    networks:
      - net

networks:
  net:
