FROM node:lts-alpine as builder

WORKDIR /app

COPY package.json .

RUN npm install

COPY . .

RUN npm run build

FROM nginx:alpine

COPY --from=builder /app/build /usr/share/nginx/html

COPY --from=builder /app/nginx.conf /etc/nginx/conf.d/default.conf

COPY --from=builder /app/ssl/self-signed.key /etc/ssl/private
COPY --from=builder /app/ssl/self-signed.crt /etc/ssl/certs
COPY --from=builder /app/ssl/dhparam.pem /etc/ssl/dhparam.pem

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]